require:
  - rubocop-performance
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

Rails:
  Enabled: true

AllCops:
  Exclude:
    - spec/support/*
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*
    - tmp/**/*
    - Guardfile
    - app/admin/**/*


Documentation:
  Enabled: false

Lint/Void:
  Exclude:
    - spec/support/**/*

HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 17

Security/JSONLoad:
  Enabled: false

Security/Open:
  Enabled: false


